on:
  push:

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Serialize workflow runs
      if: github.ref == 'refs/heads/master'
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: sync
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
# DONT-CHECKSUM-BEGIN
        - application: jira-software
          version: '8.15.0-EAP01'
          url: 'https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.15.0-EAP01.tar.gz'
          md5: '6f73d7ca889c3c5a6cd44a633e9f8f75'
          tags: '8.15.0-EAP01 8.15'
        - application: jira-software
          version: '8.14.0'
          url: 'https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.14.0.tar.gz'
          md5: 'ee80346169aa5b2a92fba8d6a40529d3'
          tags: '8.14.0 8.14 8'
        - application: jira-software
          version: '8.13.2'
          url: 'https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.13.2.tar.gz'
          md5: '2875ad1bd152689a5d5648efe1a85f1b'
          tags: '8.13.2 8.13'
        - application: confluence
          version: '7.11.0-m37'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.11.0-m37.tar.gz'
          md5: 'de7694e42bf683461f13c8642a0ace05'
          tags: '7.11.0-m37 7.11'
        - application: confluence
          version: '7.10.0'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.10.0.tar.gz'
          md5: 'ccff2f70aec819ea130a203e50a7c228'
          tags: '7.10.0 7.10 7'
        - application: confluence
          version: '7.9.3'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.9.3.tar.gz'
          md5: '5e2a674f6fb01f6f4ae42aed9c9f00ab'
          tags: '7.9.3 7.9'
        - application: confluence
          version: '7.8.3'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.8.3.tar.gz'
          md5: 'd584937e58ea1efc2652d5441df185b6'
          tags: '7.8.3 7.8'
        - application: confluence
          version: '7.7.4'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.7.4.tar.gz'
          md5: '9fffb02b0b5e1ef0a8ef35865c320f25'
          tags: '7.7.4 7.7'
        - application: confluence
          version: '7.6.2'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.6.2.tar.gz'
          md5: '7d72a1bd874bc2fb769efdce0a376c39'
          tags: '7.6.2 7.6'
        - application: confluence
          version: '7.5.2'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.5.2.tar.gz'
          md5: '3b5f6daa4dc6de0e45eddb0ed7b71611'
          tags: '7.5.2 7.5'
        - application: confluence
          version: '7.4.6'
          url: 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.4.6.tar.gz'
          md5: 'b1bb4645bf5d74ba1aa51d097afa98a0'
          tags: '7.4.6 7.4'
# DONT-CHECKSUM-END
    env:
      IMAGE_PATH: ${{ secrets.IMAGE_PATH }}${{ matrix.application }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Calculate checksum
      env:
        MD5: ${{ matrix.md5 }}
        FILES: |-
          .github/workflows/build.yml
          docker/**
          docker-shared-components/support/**
          application/${{ matrix.application }}/**
      run: |
        FILES_HASH=$(./hashFiles.py <<<${FILES})
        echo "CHECKSUM=$MD5-$FILES_HASH" >>$GITHUB_ENV
    - name: Fetch last checksum from Docker image label
      env:
        TAG: ${{ matrix.version }}
      run: |
        set -o pipefail
        (set +e; skopeo inspect "docker://${IMAGE_PATH}:${TAG}"; :) | ./last_checksum.py
    - name: Download from cache
      if: env.CHECKSUM != env.LAST_CHECKSUM
      uses: actions/cache@v2
      id: cache
      with:
        path: app.tar.gz
        key: ${{ matrix.application }}-${{ matrix.md5 }}
    - name: Download from Atlassian
      if: env.CHECKSUM != env.LAST_CHECKSUM && steps.cache.outputs.cache-hit != 'true'
      env:
        URL: ${{ matrix.url }}
      run: |
        wget --quiet --show-progress --progress=dot:giga --output-document app.tar.gz "${URL}"
    - name: Check integrity
      if: env.CHECKSUM != env.LAST_CHECKSUM
      env:
        MD5: ${{ matrix.md5 }}
      run: |
        set -o pipefail
        echo "${MD5}  app.tar.gz" | md5sum --check
    - name: Extract
      if: env.CHECKSUM != env.LAST_CHECKSUM
      run: |
        mkdir docker/app
        tar -xf app.tar.gz -C docker/app --strip-components=1 --no-same-owner
    - name: Patch
      if: env.CHECKSUM != env.LAST_CHECKSUM
      working-directory: docker/app
      run: |
        shopt -s globstar nullglob
        patch -p1 <../../application/${{ matrix.application }}/patch.diff
        mkdir -p conf/Catalina/localhost
        rm bin/**/*.bat bin/**/*.{dll,exe}{,.x64} temp/safeToDelete.tmp
    - name: Copy support scripts
      if: env.CHECKSUM != env.LAST_CHECKSUM
      run: |
        cp -lr docker-shared-components/support docker/
    - name: Copy entrypoint.sh
      if: env.CHECKSUM != env.LAST_CHECKSUM
      run: |
        cp -l application/${{ matrix.application }}/entrypoint.sh docker/
    - name: Enable dockerd --experimental for docker build --squash
      if: env.CHECKSUM != env.LAST_CHECKSUM
      run: |
        DOCKERD_CONFIG=$(jq '.+{experimental:true}' /etc/docker/daemon.json)
        sudo tee /etc/docker/daemon.json <<< "${DOCKERD_CONFIG}"
        sudo systemctl restart docker
    - name: Build Docker image
      if: env.CHECKSUM != env.LAST_CHECKSUM
      run: |
        . application/${{ matrix.application }}/build-env.sh
        APP=${app^^}
        IMAGE_ID=$(docker build --squash --quiet --label "build.checksum=${CHECKSUM}" --build-arg "APP=${APP}" --build-arg "USER=${app}" --build-arg "GROUP=${app}" --build-arg "UID_GID=${UID_GID}" --build-arg "PORT=${PORT}" --build-arg "APP_INSTALL_DIR=/opt/atlassian/${app}" --build-arg "APP_HOME=/var/atlassian/application-data/${app}" docker)
        echo "IMAGE_ID=$IMAGE_ID" >>$GITHUB_ENV
    - name: Push to Docker Hub
      if: env.CHECKSUM != env.LAST_CHECKSUM && github.ref == 'refs/heads/master'
      env:
        TAGS: ${{ matrix.tags }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        docker login --username "${REGISTRY_USERNAME}" --password "${REGISTRY_PASSWORD}" "${IMAGE_PATH%%/*}"
        for TAG in ${TAGS}; do
        	docker tag "${IMAGE_ID}" "${IMAGE_PATH}:${TAG}"
        	docker push "${IMAGE_PATH}:${TAG}"
        done
    - name: Save Docker image
      if: env.CHECKSUM != env.LAST_CHECKSUM && github.ref != 'refs/heads/master'
      run: |
        docker save -o docker-image.tar "${IMAGE_ID}"
    - name: Upload Docker image as artifact
      if: env.CHECKSUM != env.LAST_CHECKSUM && github.ref != 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.application }}_${{ matrix.version }}
        path: docker-image.tar
