on:
  schedule:
  - cron: '*/5 * * * *'
concurrency: cron
jobs:
  cron:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check latest releases from Atlassian
      run: ./check.py
    - name: Update readme
      run: ./update-readme.py
    - name: Commit if dirty
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git add --all --verbose
        if ! git diff --quiet HEAD; then
          ./update-readme.py
          git config user.name 'GitHub Actions'
          git config user.email "$(whoami)@$(hostname --fqdn)"
          git config http.https://github.com/.extraheader "Authorization: Basic $(echo -n "dummy:${PERSONAL_ACCESS_TOKEN}" | base64 --wrap=0)"
          git commit --quiet --message 'automatic commit'
          git push --quiet origin master
        fi
